/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_hc_serialport_SerialPortLib
#define _Included_com_hc_serialport_SerialPortLib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_hc_serialport_SerialPortLib_open
        (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_hc_serialport_SerialPortLib_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif